complete -c def -d 'manage fish functions/complitons'
complete -f -c def -a '(def -l)'
complete -c def -s c -l complete -d 'edit/erase/list completions instead of functions'
complete -c def -s e -l erase -d 'erase user defined functions'
complete -c def -s l -l list -d 'list user defined functions '
complete -c def -s h -l help -d 'show this help'
